= DBMS SD Version 2.0 Substantive Content Changes from v1.1
:doctype: article
:pdf-page-size: Letter

[cols="1,4",options="header"]
|===
|Field |Value
|Baseline |DBMS SD v1.1 official PDF (15 March 2023)
|Compared to |DBMS SD v2.0 Public Review Draft 1 PDF (26 June 2026)
|Generated |2026-07-22 17:34 UTC
|===

Only prose and requirement changes are shown. Headings, numbering, pagination, line wrapping, headers, footers, and relocated identical text are excluded.

== Changed content

=== Revised: Prose revision 1

Removed or replaced::
____
Foreword

the

Criteria version 3

Common

Information Technology Security Evaluation.
____

Added or replacement text::
____
Criteria:2022

IT Security.
____
=== Revised: FAU_GEN.1

Removed or replaced::
____
Guidance Documentation

information recorded
____

Added or replacement text::
____
audit data
____
=== Revised: Prose revision 3

Removed or replaced::
____
records

record.
____

Added or replacement text::
____
data

data.
____
=== Revised: Prose revision 4

Removed or replaced::
____
the
____

Added or replacement text::
____
other
____
=== Revised: FAU_SEL.1.

Removed or replaced::
____
i.

records
____

Added or replacement text::
____
data

FAU_SEL.1.
____
=== Revised: Prose revision 6

Removed or replaced::
____
NOTE: The following
____

Added or replacement text::
____
 This
____
=== Revised: Prose revision 7

Removed or replaced::
____
attributes.
____

Added or replacement text::
____
attributes associated with users.
____
=== Revised: Prose revision 8

Removed or replaced::
____
iii.

(iii).
____

Added or replacement text::
____
the test.
____
=== Revised: FMT_REV.1.1(2).

Removed or replaced::
____
i.

objects in accordance with the object security attributes, specified in FMT_REV.1.1(2).
____

Added or replacement text::
____
•

according to the DAC policy

these objects.
____
=== Revised: FMT_REV.1.1(2).

Removed or replaced::
____
ii.

a database

with sufficient privileges as allowed by the DAC policy

guidance.
____

Added or replacement text::
____
•

an authorized

rules specified in FMT_REV.1.1(2).
____
=== Revised: Prose revision 11

Removed or replaced::
____
NOTE:

(iii).
____

Added or replacement text::
____


the test.
____
=== Revised: Prose revision 12

Removed or replaced::
____
user for the evaluated configuration.

the

number of concurrent sessions

changed then

should

states that the default can be changed.
____

Added or replacement text::
____
user.

this

changed,

shall

specifies this.
____
=== Revised: Prose revision 13

Removed or replaced::
____
examine the guidance documentation and

it states

is set

the default can be changed.
____

Added or replacement text::
____
guidance describes

to set

to change it.
____
=== Revised: Prose revision 14

Removed or replaced::
____
that this number of concurrent sessions

allowed.

establish a number of sessions greater than

specified

that

concurrent

established.
____

Added or replacement text::
____
it

enforced.

exceed

created.
____
=== Revised: Prose revision 15

Removed or replaced::
____
of concurrent sessions

changed then

change the default value
____

Added or replacement text::
____
changed,

modify it
____
=== Revised: ATE_IND.2-11

Removed or replaced::
____
ETR1
____

Added or replacement text::
____
ETR
____
=== Revised: AVA_VAN.2-5

Removed or replaced::
____
ETR2
____

Added or replacement text::
____
ETR
____
=== Revised: Prose revision 18

Removed or replaced::
____
g) instructions
____

Added or replacement text::
____
Instructions

(cf.
____
=== Added: TD_DBMS_B_002

____
[TD_DBMS_B_002] Technical Decision TD_DBMS_B_002: Session Locking Mechanism Expansion, published 29 July 2025
____
=== Revised: Prose revision 20

Removed or replaced::
____
General Model CCMB-2017-04-001, Version 3.1

5, April 2017
____

Added or replacement text::
____
general model, CCMB-2022-11-001, CC:2022

1, November 2022
____
=== Revised: Prose revision 21

Removed or replaced::
____
Functional Components, CCMB-2017-049-002, Version 3.1

5, April 2017
____

Added or replacement text::
____
functional requirements, CCMB-2022-11-002, CC:2022

1, November 2022
____
=== Revised: Prose revision 22

Removed or replaced::
____
Assurance Components, CCMB-2017-04-003, Version 3.1

5, April 2017
____

Added or replacement text::
____
assurance requirements, CCMB-2022-11-003, CC:2022

1, November 2022
____
=== Revised: Prose revision 23

Removed or replaced::
____
Methodology, CCMB-2017-04-004, Version 3.1,

5, April 2017
____

Added or replacement text::
____
methodology, CCMB-2022-11-006, CEM:2022,

1, November 2022
____
=== Revised: Prose revision 24

Removed or replaced::
____
1.3, 13 March 2023
____

Added or replacement text::
____
2.0, 27 April 2026
____
=== Revised: Prose revision 25

Removed or replaced::
____
c)

technologyspecific
____

Added or replacement text::
____
technology-specific
____

