= DBMS iTC
:showtitle:
:toc:
:imagesdir: images
:icons: font
:revnumber: 1.0
:revdate: 2020-06-23

:iTC-longname: Database Managment Systems
:iTC-shortname: DBMS-iTC
:iTC-email: dbms.itc@gmail.com
:iTC-website: https://dbms-itc.github.io/
:iTC-GitHub: https://github.com/dbms-itc/

== Introduction
From the CCDB-established Working Group, the {iTC-longname} ({iTC-shortname} for short) was formed. The {iTC-shortname} consists of members of Certification Bodies, labs and vendors working together to create requirements for database security testing.

https://www.commoncriteriaportal.org/communities/database_management_systems.cfm[Common Criteria Portal {iTC-shortname} Page]

To join the {iTC-shortname}, please send a message to: {iTC-email}

== Resources related to the {iTC-longname} iTC

[GUIDANCE]
====
Currently, only the cPP and SD are available while the remaining resources are a work in progress. 
====

* link:/cPP/cPP_DBMS_V1.0.pdf[cPP v1.0]
* link:/SD/SD_DBMS_V1.0.pdf[SD v1.0]
* link:/TD/tech-dec.html[Technical Decisions]
* link:/lifecycle.html[Document Lifecycle & cPP Archives]
* link:/docs/PP-config.html[Allowed Components]
* link:/library.html[Documentation Library]
* link:/docs/public-review-process.html[Public Review Process for {iTC-shortname}]
* link:/public-review/status.html[Public Review Status]
* {iTC-GitHub}[{iTC-shortname} GitHub repository]

== Current Status
The DBMS-iTC has released the first Public Release of the collaborative Protection Profile and Supporting Document as of June 12, 2020.

