= DBMS iTC
:showtitle:
:toc:
:imagesdir: images
:icons: font
:revnumber: 1.0
:revdate: 2020-06-23

:iTC-longname: Database Managment System
:iTC-shortname: DBMS-iTC
:iTC-email: dbms.itc@gmail.com
:iTC-website: https://dbms-itc.github.io/
:iTC-GitHub: https://github.com/dbms-itc/

== Introduction
From the CCDB-established Working Group, the {iTC-longname} ({iTC-shortname} for short) was formed. The {iTC-shortname} consists of members of Certification Bodies, labs and vendors working together to create requirements for database security testing.

https://www.commoncriteriaportal.org/communities/database_management_systems.cfm[Common Criteria Portal {iTC-shortname} Page]

To join the {iTC-shortname}, please send a message to: {iTC-email}

== Current Status
The collaborative Protection Profile (cPP) version 1.3 is certified as of June 21, 2023. The accompanying Supporting Document (SD) is version 1.1.
The DBMS-iTC first published the Public Release of the collaborative Protection Profile (cPP) and Supporting Document (SD) June 12, 2020.

== Resources related to the {iTC-longname} iTC

[GUIDANCE]
====
Currently, the cPP and SD are available resources along with the GitHub repository. The iTC is working on updating this site with additional resources. 
====

* link:/cPP/cPP_DBMS_V1.0.pdf[cPP v1.3]
* link:/SD/SD_DBMS_V1.0.pdf[SD v1.1]
* {iTC-GitHub}[{iTC-shortname} GitHub repository]



